WITH CTE AS (
SELECT 

TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAY,

CASE
 WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT))IN ('Sat','Sun')
then 'WEEKEND'
ELSE 'BUSINESS_DAY' 
END AS DAY_STATUS,
CASE 
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
THEN 'SPRING'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8)
THEN 'SUMMER'
ELSE 'AUTUMN'
END AS STATION_OF_THE_YEAR


FROM 
{{ source('demo', 'bike') }}
WHERE STARTED_AT!='started_at'

)

select 
*
from CTE